### ISSUE TITLE
Messages and project root

### ISSUE THREAD

**Issue by deadtrickster** [s-kostyaev/ivy-erlang-complete#8]
Hi,

Cool package, thank you for this!

However I find a couple of tiny things a bit annoying:

1. "Erlang completions updated" message. Very noisy, now I just comment these. Are they really necessary?
2. I had to add this line: `(setq-local ivy-erlang-complete-project-root (projectile-project-root))` to my erlang configuration. I think `projectile-project-root` can be reasonable default for everyone (at least that's what other similar packages have as default).

**Comment by deadtrickster** [comment]
Also feature request:
goto-definition for imported functions.

**Comment by s-kostyaev** [comment]
Hi,
Thanks for your interest.
1. Not really necessary, I can create customizable flag for this disabled by default.
2. I don't think this is best default because of many projects I work on can't work with this settings. That was projects with multiple git repos. Better default for me is some heuristic with rebar config. But you can set what you find more usable to your configuration.

Can you attach sample where go-to definition not work for imported functions? It should work out of the box.

**Comment by s-kostyaev** [comment]
Also I can do all of it not just now - I haven't time now. You need to wait some time.

**Comment by s-kostyaev** [comment]
@deadtrickster feel free to reopen it or create new issue with attached sample with broken goto-definition for imported functions.
